version: "3"

services:
  db:
    container_name: "${PROJECT_NAME}-db"
    image: mysql:5.7
    volumes:
      - "$PWD/wp_db:/var/lib/mysql"
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - wpnet

  wp:
    container_name: "${PROJECT_NAME}-web"
    volumes:
      - "$PWD/wp_app:/var/www/html"
    depends_on:
      - db
    image: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_POST_REVISIONS', 4 );
        define( 'WP_HOME', 'http://localhost' );
        define( 'WP_SITEURL', 'http://localhost' );
    networks:
      - wpnet

  admin:
    depends_on:
      - db
    container_name: "${PROJECT_NAME}-admin"
    image: phpmyadmin
    environment:
      DATABASE_HOST: "db:${MYSQL_PORT}"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - wpnet

networks:
  wpnet:
    name: "${PROJECT_NAME}_net"
